services:

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui

    container_name: rag_chat_ui

    ports:
      - "8501:8501"
      - "8001:8001"

    env_file:
      - .env

    restart: unless-stopped
  
  prometheus:
    image: prom/prometheus:latest

    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"

    depends_on:
      - ui

    restart: unless-stopped
  
  grafana:
    image: grafana/grafana-oss:latest

    container_name: grafana

    ports:
      - "3000:3000"

    volumes:
      - grafana-storage:/var/lib/grafana

    depends_on:
      - prometheus

    restart: unless-stopped

volumes:
  grafana-storage:
  prometheus-storage: